// 共享库入口：agent 对话领域的全部公共导出。
export {
  AgentAbortError,
  DEFAULT_SYSTEM_PROMPT,
  runAgentLoop,
  trimHistory,
  type AgentLoopDeps,
  type AgentLoopEvent,
  type AgentLoopOptions,
  type AgentLoopResult,
  type AgentTool,
  type ChatMessage,
  type ChatRole,
  type LlmChatClient,
  type ToolCallRequest,
} from './agent-loop';
export {
  API_PATH_EMPTY_HINT,
  createAnthropicClient,
  createLlmClient,
  createOpenAiCompatClient,
  toAnthropicMessages,
  toWireMessages,
  toWireTools,
  type LlmConfig,
  type LlmLogFn,
} from './llm-client';
export {
  ABORTED_TURN_TEXT,
  createChatController,
  type ChatController,
  type ChatControllerDeps,
  type ChatTurnView,
} from './chat-controller';
export {
  DEFAULT_ACTIVE_AGENT_ID,
  LEGACY_DEFAULT_AGENT_ID,
  composeSystemPrompt,
  createBuiltinAgentProfiles,
  getActiveAgent,
  mergeLlmConfig,
  migrateLegacySettings,
  validateAgentProfilesState,
  type AgentLlmOverride,
  type AgentProfile,
  type AgentProfilesState,
  type AgentRuleItem,
  type AgentRules,
  type AgentSkillRef,
  type ProfileStore,
} from './agent-profile';
export {
  SKILL_L1_TOKEN_BUDGET,
  SKILL_TOOL_NAME,
  buildSkillL1Section,
  createSkillResolver,
  createSkillToolDefinition,
  estimateTokens,
  matchSkillTriggers,
  parseSkillToolArgs,
  toSkillToolError,
  toSkillToolResult,
  type SkillDefinition,
  type SkillResolver,
  type SkillResolverDeps,
  type SkillSummary,
  type SkillToolResult,
} from './skill-loader';
