// 共享库入口：agent 对话领域的全部公共导出。
export {
  A2aClientError,
  A2A_REQUEST_TIMEOUT_MS,
  createA2aClient,
  type A2aClient,
  type A2aClientDeps,
  type A2aClientErrorKind,
  type A2aRequestOptions,
  type A2aSendResult,
} from './a2a-client';
export {
  isHttpUrl,
  isTerminalTaskState,
  messageToText,
  partToText,
  validateA2aTask,
  validateAgentCard,
  type A2aDataPart,
  type A2aFilePart,
  type A2aMessage,
  type A2aPart,
  type A2aTask,
  type A2aTaskState,
  type A2aTaskStatus,
  type A2aTextPart,
  type AgentCard,
  type AgentCardCapabilities,
  type AgentCardInterface,
  type AgentCardSkill,
} from './a2a-types';
export {
  A2A_POLL_INTERVAL_MS,
  A2A_POLL_MAX_ATTEMPTS,
  A2A_SEND_TASK_SUFFIX,
  A2A_SEND_TIMEOUT_MS,
  A2A_TOOL_PREFIX,
  buildA2aSendTaskTool,
  buildA2aToolDescription,
  buildA2aToolName,
  createA2aToolSource,
  parseA2aToolName,
  validateA2aAgentId,
  type A2aAgentConfig,
  type A2aToolResult,
  type A2aToolSource,
  type A2aToolSourceDeps,
} from './a2a-tool-source';
export {
  AgentAbortError,
  DEFAULT_SYSTEM_PROMPT,
  runAgentLoop,
  trimHistory,
  type AgentLoopDeps,
  type AgentLoopEvent,
  type AgentLoopOptions,
  type AgentLoopResult,
  type AgentTool,
  type ChatMessage,
  type ChatRole,
  type LlmChatClient,
  type ToolCallRequest,
} from './agent-loop';
export {
  API_PATH_EMPTY_HINT,
  createAnthropicClient,
  createLlmClient,
  createOpenAiCompatClient,
  toAnthropicMessages,
  toWireMessages,
  toWireTools,
  type LlmConfig,
  type LlmLogFn,
} from './llm-client';
export {
  ABORTED_TURN_TEXT,
  createChatController,
  type ChatController,
  type ChatControllerDeps,
  type ChatTurnView,
} from './chat-controller';
export {
  DEFAULT_ACTIVE_AGENT_ID,
  LEGACY_DEFAULT_AGENT_ID,
  composeSystemPrompt,
  createBuiltinAgentProfiles,
  getActiveAgent,
  mergeLlmConfig,
  migrateLegacySettings,
  validateAgentProfilesState,
  type AgentLlmOverride,
  type AgentProfile,
  type AgentProfilesState,
  type AgentA2aRef,
  type AgentRuleItem,
  type AgentRules,
  type AgentSkillRef,
  type ProfileStore,
} from './agent-profile';
export {
  SKILL_L1_TOKEN_BUDGET,
  SKILL_TOOL_NAME,
  buildSkillL1Section,
  createSkillResolver,
  createSkillToolDefinition,
  estimateTokens,
  matchSkillTriggers,
  parseSkillToolArgs,
  toSkillToolError,
  toSkillToolResult,
  type SkillDefinition,
  type SkillResolver,
  type SkillResolverDeps,
  type SkillSummary,
  type SkillToolResult,
} from './skill-loader';
